### ISSUE TITLE
Some quick feedback for DG at mid-v1.4:

### ISSUE THREAD

**Issue by eugenepeh** [CS2103-AY1819S1-T09-4/main#132]
* Are you guys still using CommandHistory? Not sure if its your team who have removed undo/redo feature.
![image](https://user-images.githubusercontent.com/19277206/48275427-6b2f2a00-e480-11e8-9619-2f8d9c438879.png)
* Problem areas spotted in diagrams (drawn in red) :
![image](https://user-images.githubusercontent.com/19277206/48275368-49ce3e00-e480-11e8-87bc-19beb4da5b0c.png)
![image](https://user-images.githubusercontent.com/19277206/48275527-a92c4e00-e480-11e8-88d5-afc01ba9a988.png)
* Can probably use same capitalization
![image](https://user-images.githubusercontent.com/19277206/48275595-d8db5600-e480-11e8-9b1a-99e92b0e1b73.png)

* Is this still in your app?
![image](https://user-images.githubusercontent.com/19277206/48275566-c4975900-e480-11e8-8049-fc3f532f6443.png)

**Comment by ZhuanYu** [comment]
Fixed in #134
